version: '3.8'

services:
  app1:
    build: ./app
    depends_on:
      - mongodb

  app2:
    build: ./app
    depends_on:
      - mongodb

  app3:
    build: ./app
    depends_on:
      - mongodb

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/init-db:/docker-entrypoint-initdb.d
volumes:
  mongodata:
